INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(LIBYUNSDR_PKG libyunsdr)
PKG_CHECK_MODULES(LIBYUNSDR_PKG libyunsdr_ss)

FIND_PATH(
    LIBYUNSDR_INCLUDE_DIRS
    NAMES yunsdr_api.h
    PATHS /usr/local/include
          /usr/include
          ${LIBYUNSDR_PKG_INCLUDE_DIRS}
)

FIND_LIBRARY(
	LIBYUNSDR_LIBRARIES
    NAMES yunsdr
    PATHS /usr/local/lib
          /usr/lib
          ${LIBYUNSDR_PKG_LIBRARY_DIRS}
)

FIND_PATH(
    LIBYUNSDR_SS_INCLUDE_DIRS
    NAMES yunsdr_api_ss.h
    PATHS /usr/local/include
          /usr/include
          ${LIBYUNSDR_PKG_INCLUDE_DIRS}
)

FIND_LIBRARY(
	LIBYUNSDR_SS_LIBRARIES
    NAMES yunsdr_ss
    PATHS /usr/local/lib
          /usr/lib
          ${LIBYUNSDR_PKG_LIBRARY_DIRS}
)

if(LIBYUNSDR_INCLUDE_DIRS AND LIBYUNSDR_LIBRARIES)
  message(STATUS "Found libyunsdr: ${LIBYUNSDR_INCLUDE_DIRS}, ${LIBYUNSDR_LIBRARIES}")
else(LIBYUNSDR_INCLUDE_DIRS AND LIBYUNSDR_LIBRARIES)
  message(STATUS "libyunsdr not found.")
endif(LIBYUNSDR_INCLUDE_DIRS AND LIBYUNSDR_LIBRARIES)

if(LIBYUNSDR_SS_INCLUDE_DIRS AND LIBYUNSDR_SS_LIBRARIES)
  message(STATUS "Found libyunsdr_ss: ${LIBYUNSDR_SS_INCLUDE_DIRS}, ${LIBYUNSDR_SS_LIBRARIES}")
else(LIBYUNSDR_SS_INCLUDE_DIRS AND LIBYUNSDR_SS_LIBRARIES)
  message(STATUS "libyunsdr_ss not found.")
endif(LIBYUNSDR_SS_INCLUDE_DIRS AND LIBYUNSDR_SS_LIBRARIES)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBYUNSDR DEFAULT_MSG LIBYUNSDR_LIBRARIES LIBYUNSDR_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBYUNSDR_LIBRARIES LIBYUNSDR_INCLUDE_DIRS)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBYUNSDR DEFAULT_MSG LIBYUNSDR_SS_LIBRARIES LIBYUNSDR_SS_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIBYUNSDR_SS_LIBRARIES LIBYUNSDR_SS_INCLUDE_DIRS)

